### ISSUE TITLE
Add support for scene color without scene color node

### ISSUE THREAD

**Issue by smitdylan2001** [andypoly/UnityShaderGraphCustomFunctions#1]
You said you need the scene color node in the graph in order for the hlsl code to support scene color.

While debugging I found that you can add a keyword bool in order to support this without the scene color node: 
![image](https://github.com/user-attachments/assets/1d5fac5a-b0ef-4b13-a264-e5a115fb9828)

**Comment by andypoly** [comment]
OK indeed it does work thanks - very odd!
